version: "3.1"

services:
  dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/var/app
    depends_on:
      - postgres
    env_file:
      - config/database.env
    links:
      - postgres

  core:
    container_name: core-api
    build:
      context: packages/core
      dockerfile: ../../docker/nodejs/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./packages/core:/var/app
    env_file:
      - config/database.env
      - config/core.env
    links:
      - postgres

  postgres:
    image: postgres
    env_file:
      - config/database.env
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d

